import urllib
import simplejson as json

def do_call(methodstr):
	urlstr='http://ws.audioscrobbler.com/2.0/?api_key=a9785e0b1bb8deb9eb4e090b3aba9613'+'&'+methodstr
	urlstr+='&format=json'
	resp=urllib.urlopen(urlstr)
	response = json.loads(resp.read())
	return response

'''
{u'artist': {u'bio': {u'content': u'There are eight artists with this name:\n 1. a popular French electronic music duo\n 2. a Belgian hardcore band\n 3. a German thrash metal band\n 4. an English drum \'n\' bass producer\n 5. an Irish folk band\n 6. a reggae musician\n 7. a Croatian thrash metal band\n 8. a Swedish musician\n \n <strong>1)</strong> Justice  is an electronic music duo from Paris, France, formed in 2003 and consisting of <a href="http://www.last.fm/music/Gaspard+Aug%C3%A9" class="bbcode_artist">Gaspard Aug&eacute;</a> (born 21 May, 1979) and <a href="http://www.last.fm/music/Xavier+de+Rosnay" class="bbcode_artist">Xavier de Rosnay</a> (born 2 July, 1982). They are mostly known for their remix of <a href="http://www.last.fm/music/Simian" class="bbcode_artist">Simian</a>\u2019s \u201cNever Be Alone\u201d, later renamed \u201cWe Are Your Friends\u201d, as well as their \u201cWaters of Nazareth\u201d EP and their single release of \u2018\u2019D.A.N.C.E.\u2019\u2018. Their debut album is entitled \u201c\u2020\u201d but is often spelled out \u201cCross\u201d. Justice are the most commercially successful act on the label of Pedro Winter (Busy P), <a href="http://www.last.fm/label/Ed+Banger/" class="bbcode_label">Ed Banger</a>.\n \n You know Justice, AKA Xavier de Rosnay and Gaspard Auge. French duo, remixed Simian to create the titanic \'We Are Your Friends\', the anthem-that-will-not-die, the iceberg tune (big on top, massive underneath) that\'s wrecked dancefloors from backstage Glasto to Trash to Euro-resorts and back again. That\'s still rippling across radio airwaves as I t- t- t- type. You know Justice. Groovy Parisians, rerubbed Franz Ferdinand and Britney Spears (\'her vocal was the best a capella we ever heard. She is not a faker. It is not by chance that she is a big pop star\') and Mystery Jets and Fatboy Slim, blew the wheels off club culture then welded them back on upside down. Don\'t wear robot masks.\n \n Justice, on the other hand, don\'t really know Justice. They got here by mistake. They are accidental heroes. They didn\'t mean to become genius producers. They don\'t know what they\'re doing. That\'s why they\'re so good at doing what they\'re doing. Way back when - like, four or five fast years ago - Xavier de Rosnay and Gaspard Auge were two graphic designers. \'In Paris everybody is a graphic designer, or a DJ,\' says Xavier, socio-pithily, \'and wearing a leather jacket and having straight hair. In all our friends, 60 are graphic designers and the rest are doing electronic music.\'\n \n For the first three years of Justice\'s existence, the pair based themselves in Xavier\'s bedroom. They signed to discerning Paris label Ed Banger and released an EP, Waters Of Nazareth, the title track a big, fuzzy-feedbacky monster of disco-blippery. They were making it up as they went along.\u2028 Xavier: \u2018Between making We Are Your Friends and Waters Of Nazareth, there was the discovery of new tools to make music - the computer and the things you can make with it. The Apple Mac, this is our main progress.\'\n \n For their debut album Justice decided they needed to escape Xavier\'s bedroom. They rented a cheap basement in the centre of Paris, fixed it up a little, and installed what kit they had. Gaspard: \'Basic equipment. Really, really basic. We made this album with equipment that everyone can afford, can find easily. We don\'t have enough knowledge of sound engineering and things to use really fancy equipment. That\'s what makes it exciting for us - just to do music without really knowing how to do it.\' And Lord, what excitement Justice serve up on their debut album. Genesis kicks things off with a big fat squelch, before Let There Be Light hovers into view like Jean Michel Jarre piloting that huge fuck-off UFO in Close Encounters Of The Third Kind. Justice insist they won\'t be offended at comparisons with the knob-twiddling maestro of French synth-fromage.\u2028 \'He was a pioneer in making electronic pop records,\' says Gaspard. \'Even if he was bad taste we like the comparison.\' \u2018This tune was made with old and cheap analogue synthesisers,\' says Xavier.\n \n <strong>2)</strong> <a href="http://www.last.fm/music/Justice" class="bbcode_artist">Justice</a> In the summer of 2003 a couple of young hardcore enthusiasts put their heads together and decided to create a band that would stir things up and speak out. Bummed out but at the same time motivated by the stale state of affairs in hardcore at the time, JUSTICE burst onto the scene with an unseen energy, a righteous attitude and the determination to turn things around. More than three years down the line and after some line up changes, a slew of well received releases (their demo, two EP\'s and a full length) and countless tours and shows (in Europe and the States), it is safe to say their mission\'s been accomplished. JUSTICE has become a household name to hardcore/punk kids worldwide and they have accomplished that by doing what they do best: writing catchy, honest and meaningful songs and backing it all up with an insane work ethic.\n \n What all the nay-sayers and know-it-alls had to say never phased JUSTICE. They just continued to work hard and never looked back. For them, this isn\'t about being cool or receiving praise... It is about a love for hardcore in all its aspects and a will to be heard. Not content with sitting back and waiting for things to happen, they have put out most of their own records and booked most of their own tours. Not afraid of change, the have continued to broaden their sound with every release, challenging themselves and the listener to take things a few steps further every time. Sure, the energy still oozes from the cracks and that youthful anger is still there, but through the years JUSTICE\'s sound has become more melodic, soulful and grooving.\n \n For their second full length album, &quot;Escapades&quot;, JUSTICE decided to team up with Reflections Records from Holland. This hardworking and well respected label will definitely make sure that the band\'s unique sound and message gets out to everyone wants to hear it and everyone that loves their hardcore true and authentic. &quot;Escapades&quot; is a record that needs to be heard. It deserves to be heard because it is genuine, honest and strong. A relief in these days of pre-packaged angst and anger. A breath of fresh air among the so many bands that just go through the motions. Simply put, &quot;Escapades&quot; is their most daring and challenging record to date. JUSTICE have gone all the way, both musically and lyrically, to give us 110 percent. Nothing less. They\'ve put their hearts on display and have dug deeper than ever to write the best bunch of songs they possibly could.\n \n Two of these songs could already be heard on 2006\'s &quot;Up And Down/Push It To Edge&quot; EP, which already served as a good indication of what was still to come. This is a record that will take some getting used to and will only reveal its true power after several spins. Once it grabs a hold of you though, it won\'t let go. From the anthemic and infectious opener &quot;I Need Air&quot; (featuring Richie Birkenhead on guest vocals), through the heavily grooving &quot;Unsure&quot; and all the way to the introspective and surprisingly mellow last song titled &quot;Oh How We Laughed&quot;, &quot;Escapades&quot; is one hell of a record. It twists and turns, slows down and speeds up, all at the right times. It is melodic, but never weak. It is honest and emotional, but never corny or lame. &quot;Escapades&quot; is who JUSTICE were Honest. Strong. True. \n \n Justice Played their last show the 8th of March 2008 and released one final 12&quot; ep along with their demise.\n \n Justice released two LPs, two 7 inches and a 12&quot; EP. Members are now in <a href="http://www.last.fm/music/Rhythm+To+The+Madness" class="bbcode_artist">Rhythm To The Madness</a>, <a href="http://www.last.fm/music/Loud+And+Clear" class="bbcode_artist">Loud And Clear</a> and <a href="http://www.last.fm/music/Rise+and+Fall" class="bbcode_artist">Rise and Fall</a>. <a href="http://www.myspace.com/justicehc" rel="nofollow">http://www.myspace.com/justicehc</a>.\n \n FTS \u2013 vocals\n Stief \u2013 guitar\n Daan \u2013 drums\n Sike \u2013 bass\n \n Website: <a href="http://www.justicehc.com" rel="nofollow">www.justicehc.com</a>\n E-mail: intro_justice@hotmail.com \n \n <strong> 3)</strong> Justice is a thrash/death metal band from Franconia, Germany. The band was founded in 1993. You can visit their homepage at <a href="http://www.justiceweb.de" rel="nofollow">http://www.justiceweb.de</a>. In 2003 and 2006 the band started the Earthshaker Festival.\n \n <strong> 4)</strong> <a href="http://www.discogs.com/artist/Justice" rel="nofollow">Justice</a> is Anthony Bowes, aka Tony Justice, a drum \'n\' bass producer . Justice produced with <a href="http://www.last.fm/music/Blame" class="bbcode_artist">Blame</a> from 1991-1996, mainly on the Moving Shadow record label.  They also produced together under the alias <a href="http://www.last.fm/music/Icons" class="bbcode_artist">Icons</a>. \n \n <strong> 5)</strong> Justice is also an Irish Folk band, about which fairly few things are known. Their track &quot;They Shoot Children&quot; is one of the more renowned tracks and yet, internet culture doesn\'t tell much about this artist.\n \n <strong> 6)</strong> Justice is a reggae artist\n \n <strong> 7)</strong> Justice is thrash metal band from Virovitica, Croatia. They recorded one demo album called &quot;Antariksh Expands&quot; in 1994. Band is merely mentioned here: <a href="http://www.cmar-net.org/bandovi/band_panonski.htm" rel="nofollow">http://www.cmar-net.org/bandovi/band_panonski.htm</a>[\n \n <strong> 8)</strong> Justice is the name of the solo project of Anders Pierson. He has released one EP to date, &quot;2008: The Singles,&quot; unfortunately it has not yet reached the internet, instead being released only through cassette tapes.',
                      u'published': u'Tue, 12 Oct 2010 17:51:51 +0000',
                      u'summary': u'There are eight artists with this name:\n 1. a popular French electronic music duo\n 2. a Belgian hardcore band\n 3. a German thrash metal band\n 4. an English drum \'n\' bass producer\n 5. an Irish folk band\n 6. a reggae musician\n 7. a Croatian thrash metal band\n 8. a Swedish musician  1) Justice  is an electronic music duo from Paris, France, formed in 2003 and consisting of <a href="http://www.last.fm/music/Gaspard+Aug%C3%A9" class="bbcode_artist">Gaspard Aug&eacute;</a> (born 21 May, 1979) and <a href="http://www.last.fm/music/Xavier+de+Rosnay" class="bbcode_artist">Xavier de Rosnay</a> (born 2 July, 1982).'},
             u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/13973537.jpg',
                         u'size': u'small'},
                        {u'#text': u'http://userserve-ak.last.fm/serve/64/13973537.jpg',
                         u'size': u'medium'},
                        {u'#text': u'http://userserve-ak.last.fm/serve/126/13973537.jpg',
                         u'size': u'large'},
                        {u'#text': u'http://userserve-ak.last.fm/serve/252/13973537.jpg',
                         u'size': u'extralarge'},
                        {u'#text': u'http://userserve-ak.last.fm/serve/_/13973537/Justice.jpg',
                         u'size': u'mega'}],
             u'mbid': u'444f2191-8841-440e-bbc1-6fd564893946',
             u'name': u'Justice',
             u'similar': {u'artist': [{u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/32827587.png',
                                                   u'size': u'small'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/64/32827587.png',
                                                   u'size': u'medium'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/126/32827587.png',
                                                   u'size': u'large'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/252/32827587.png',
                                                   u'size': u'extralarge'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/_/32827587/Busy+P+busyp.png',
                                                   u'size': u'mega'}],
                                       u'name': u'Busy P',
                                       u'url': u'http://www.last.fm/music/Busy+P'},
                                      {u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/20641483.jpg',
                                                   u'size': u'small'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/64/20641483.jpg',
                                                   u'size': u'medium'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/126/20641483.jpg',
                                                   u'size': u'large'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/252/20641483.jpg',
                                                   u'size': u'extralarge'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/500/20641483/Sebastian+pantiero2.jpg',
                                                   u'size': u'mega'}],
                                       u'name': u'Sebastian',
                                       u'url': u'http://www.last.fm/music/Sebastian'},
                                      {u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/15180263.jpg',
                                                   u'size': u'small'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/64/15180263.jpg',
                                                   u'size': u'medium'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/126/15180263.jpg',
                                                   u'size': u'large'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/252/15180263.jpg',
                                                   u'size': u'extralarge'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/500/15180263/Boys+Noize++Live.jpg',
                                                   u'size': u'mega'}],
                                       u'name': u'Boys Noize',
                                       u'url': u'http://www.last.fm/music/Boys+Noize'},
                                      {u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/8477385.jpg',
                                                   u'size': u'small'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/64/8477385.jpg',
                                                   u'size': u'medium'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/126/8477385.jpg',
                                                   u'size': u'large'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/252/8477385.jpg',
                                                   u'size': u'extralarge'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/_/8477385/MSTRKRFT.jpg',
                                                   u'size': u'mega'}],
                                       u'name': u'MSTRKRFT',
                                       u'url': u'http://www.last.fm/music/MSTRKRFT'},
                                      {u'image': [{u'#text': u'http://userserve-ak.last.fm/serve/34/49457161.png',
                                                   u'size': u'small'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/64/49457161.png',
                                                   u'size': u'medium'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/126/49457161.png',
                                                   u'size': u'large'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/252/49457161.png',
                                                   u'size': u'extralarge'},
                                                  {u'#text': u'http://userserve-ak.last.fm/serve/_/49457161/Daft+Punk+Face+To+Face.png',
                                                   u'size': u'mega'}],
                                       u'name': u'Daft Punk',
                                       u'url': u'http://www.last.fm/music/Daft+Punk'}]},
             u'stats': {u'listeners': u'827457', u'playcount': u'27344191'},
             u'streamable': u'1',
             u'tags': {u'tag': [{u'name': u'electronic',
                                 u'url': u'http://www.last.fm/tag/electronic'},
                                {u'name': u'electro',
                                 u'url': u'http://www.last.fm/tag/electro'},
                                {u'name': u'french',
                                 u'url': u'http://www.last.fm/tag/french'},
                                {u'name': u'dance',
                                 u'url': u'http://www.last.fm/tag/dance'},
                                {u'name': u'electronica',
                                 u'url': u'http://www.last.fm/tag/electronica'}]},
             u'url': u'http://www.last.fm/music/Justice'}}
'''